name: cint pipeline

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Compile
        run: |
          env
          cmake -DWITH_RANGE_COULOMB=1 -DWITH_COULOMB_ERF=1 -DWITH_F12=1 -Bbuild -DKEEP_GOING=1 .
          cmake --build build
          pip install numpy mpmath pyscf
      - name: Test for rys-roots
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd ${{ github.workspace }}/tests
          python test_rys_roots.py
      - name: Unittest
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd ${{ github.workspace }}/tests
          for i in test_cint.py test_3c2e.py test_int2e.py; do
            echo $i
            curl -O https://raw.githubusercontent.com/sunqm/libcint/master/testsuite/$i
            python $i --quick
          done
          for i in test_c2s.py test_int1e_grids.py test_int1e.py test_int2c2e.py test_int3c1e.py; do
            echo $i
            curl -O https://raw.githubusercontent.com/sunqm/libcint/master/testsuite/$i
            python $i
          done
